name = "Dartis-Craft - Stargate Network 206 AIO Base Modpack"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05d14768bf21c76fa8cc9ee8e14d89b408da2ddd3c0e51509de85b6eceb2724d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
